#!/usr/bin/env bash
#
# sync-google-skills.sh — vendor selected skill directories from google/adk-python
# into this repo's skills/ directory as a read-only mirror.
#
# Source : https://github.com/google/adk-python  (Apache-2.0)
# Usage  : scripts/sync-google-skills.sh [ref-or-sha]    # default ref: main
#
# Each run wipes and re-copies the target directories so they exactly match
# upstream at the resolved commit. DO NOT edit the vendored directories by hand —
# changes are overwritten on the next sync. To pin a specific version, pass a
# commit SHA or tag as the first argument, e.g.
#   scripts/sync-google-skills.sh 0337d19c479077b8dc8d49cb8c1ba54bc7cae710
#
set -euo pipefail

REPO_URL="https://github.com/google/adk-python"
DEFAULT_REF="main"

# Source path (in upstream) -> destination path (relative to this repo's root).
# Add a line here to vendor another directory; the destination encodes the rename.
SKILLS=(
  ".agents/skills/adk-architecture|skills/google-adk-architecture"
  ".agents/skills/adk-agent-builder|skills/google-adk-agent-builder"
)

# Upstream license file, copied verbatim for attribution compliance.
LICENSE_SRC="LICENSE"
LICENSE_DEST="licenses/google-adk-python-LICENSE.txt"

REF="${1:-$DEFAULT_REF}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TODAY="$(date -u +%Y-%m-%d)"

# --- fetch upstream into a throwaway sparse checkout -------------------------
TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

echo "→ Fetching $REPO_URL @ $REF ..."
git -C "$TMP" init -q
git -C "$TMP" remote add origin "$REPO_URL"
git -C "$TMP" sparse-checkout init --cone          # cone mode: root files (incl. LICENSE) come along

sparse_paths=()
for entry in "${SKILLS[@]}"; do
  sparse_paths+=("${entry%%|*}")
done
git -C "$TMP" sparse-checkout set "${sparse_paths[@]}"
git -C "$TMP" fetch -q --depth 1 origin "$REF"     # works for a branch, tag, or full SHA on GitHub
git -C "$TMP" checkout -q FETCH_HEAD

SHA="$(git -C "$TMP" rev-parse HEAD)"
echo "→ Resolved $REF to $SHA"

# --- mirror each skill directory --------------------------------------------
for entry in "${SKILLS[@]}"; do
  src="${entry%%|*}"
  dest="${entry##*|}"
  src_abs="$TMP/$src"
  dest_abs="$REPO_ROOT/$dest"

  if [[ ! -d "$src_abs" ]]; then
    echo "✗ Source directory not found upstream: $src" >&2
    exit 1
  fi

  skill_name="$(basename "$dest")"

  echo "→ Mirroring $src -> $dest"
  rm -rf "$dest_abs"
  mkdir -p "$dest_abs"
  cp -R "$src_abs/." "$dest_abs/"

  # Rename the skill to match its vendored directory: rewrite the `name:` field
  # in the SKILL.md front matter (first front-matter block only). Idempotent —
  # each run re-copies the pristine upstream file before rewriting. awk is used
  # instead of `sed -i` to avoid the BSD/GNU in-place-flag difference.
  if [[ -f "$dest_abs/SKILL.md" ]]; then
    awk -v newname="$skill_name" '
      /^---[[:space:]]*$/        { fence++; print; next }
      fence == 1 && !done && /^name:[[:space:]]/ { print "name: " newname; done=1; next }
                                  { print }
    ' "$dest_abs/SKILL.md" > "$dest_abs/SKILL.md.tmp"
    mv "$dest_abs/SKILL.md.tmp" "$dest_abs/SKILL.md"
  fi

  # Provenance marker. This file is our addition (not upstream) and makes the
  # "read-only mirror" contract visible to anyone who opens the directory.
  cat > "$dest_abs/VENDORED.md" <<EOF
# Vendored from google/adk-python

**Do not edit by hand.** This directory is a read-only mirror regenerated by
\`scripts/sync-google-skills.sh\`; local changes are overwritten on the next sync.

- Source: $REPO_URL/tree/$SHA/$src
- Commit: \`$SHA\`
- License: Apache-2.0 (see \`licenses/google-adk-python-LICENSE.txt\`)
- Synced: $TODAY
- Modifications from upstream: directory renamed to \`$skill_name\`; the \`name:\`
  field in \`SKILL.md\` was updated to match.
EOF
done

# --- preserve upstream license text -----------------------------------------
mkdir -p "$REPO_ROOT/$(dirname "$LICENSE_DEST")"
cp "$TMP/$LICENSE_SRC" "$REPO_ROOT/$LICENSE_DEST"

# --- (re)generate the attribution file --------------------------------------
{
  cat <<EOF
# Third-Party Licenses

This project bundles ("vendors") source code from third-party open-source
projects. Each component below is redistributed under its own license, a copy of
which is included in the \`licenses/\` directory.

This file is generated by \`scripts/sync-google-skills.sh\` — do not edit by hand.

---

## google/adk-python

- Source: $REPO_URL
- Commit: \`$SHA\`
- Synced: $TODAY
- License: Apache-2.0 — see \`licenses/google-adk-python-LICENSE.txt\`
- Vendored paths:
EOF
  for entry in "${SKILLS[@]}"; do
    echo "    - ${entry##*|}  (from ${entry%%|*})"
  done
  cat <<EOF
- Modifications: vendored directories renamed with a \`google-\` prefix; the
  \`name:\` field in each \`SKILL.md\` updated to match its directory; a
  \`VENDORED.md\` provenance marker added to each.
EOF
} > "$REPO_ROOT/THIRD_PARTY_LICENSES"

# --- summary ----------------------------------------------------------------
echo
echo "✓ Sync complete."
echo "  Repo:        $REPO_URL"
echo "  Commit:      $SHA"
echo "  License:     Apache-2.0"
for entry in "${SKILLS[@]}"; do
  echo "  Mirrored:    ${entry##*|}"
done
echo "  Attribution: THIRD_PARTY_LICENSES + $LICENSE_DEST"
